Amy/tamales
bananabrann/recipes.brannan.cloud pull request #25
Opened 2023-10-16 21:06 UTC by Amy-Hailu

resolves #20

2023-10-16 21:55 UTC, spideyIII reviewed
You seem to add a Ul inside of an existing Ul so clean your code.

2023-10-16 22:23 UTC, bananabrann requested changes

2023-10-16 22:23 UTC, bananabrann commented on src/routes/mexican/tamales/+page.svelte
Good work putting your own take on it with the `h3` tags. However, let's remove the colons

```svelte
<h3>For the Dough</h3>
```

2023-10-16 22:24 UTC, bananabrann commented
Give the PR a better name please

2023-10-17 16:07 UTC, bananabrann approved these changes

2023-10-17 16:15 UTC, spideyIII approved these changes

2023-10-17 16:17 UTC, merged